// Deno Code
/* Warning!. This value is used in instantiation. You can modify, but don't delete. */
const moduleInstantiationParameters = {
  noInitialRun: false
};

/*_BEGIN_MODULE_INSTANTIATION_*/
//The provided code is autogenerated. Do not modify/delete.
/*_END___MODULE_INSTANTIATION_*/

/* Your code here/below */
console.log("Finished!");